version: '3'
services:
  tradfri:
    build: .
    image: mxmlnznr/tradfri-server:latest
    ports:
      - 5000:5000
    restart: always
    environment:
      FLASK_ENV: production
      TRADFRI_ID: ${TRADFRI_ID}
      TRADFRI_PSK: ${TRADFRI_PSK}
      TRADFRI_IP: ${TRADFRI_IP}